name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-app
      REGISTRY: ghcr.io/ibraheemcisse  # or docker.io/yourdockerhubusername
      K8S_NAMESPACE: default

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

- name: Log in to GitHub Container Registry
  uses: docker/login-action@v3
  with:
    registry: ghcr.io
    username: ${{ secrets.GHCR_USERNAME }}
    password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Configure kubectl with Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f ./k8s/production

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/${{ env.IMAGE_NAME }} --namespace ${{ env.K8S_NAMESPACE }}
